### ISSUE TITLE
Is there a way to load remote LUT? 

### ISSUE THREAD

**Issue by Parth-Patoliya** [FluidGroup/Brightroom#139]

**Comment by muukii** [comment]
Yes, there is.

As you can see from this documentation, you can load LUT from anywhere.
https://www.notion.so/muukii/Creating-your-own-filters-LUT-d1942f2f5bcc44d88481d0a0cc4aacb3#cd76a9a88bfe435bae83348b6ffcbbf2

**Comment by muukii** [comment]
Sorry, currently loading from bundle only.
But I will try to make it can load from anywhere.

**Comment by muukii** [comment]
I figured out to create filter from LUT that loaded from remote.

- Load the image for LUT
- Save it to anywhere you want
- Get the path to that

```swift
let filter = FilterColorCube(
  name: /* name */,
  identifier: /* ensure get a unique identifier*/,
  lutImage: /* create an instance */,
  dimension: 64 /* it's depends on your LUT */
)

https://www.notion.so/muukii/Creating-your-own-filters-LUT-d1942f2f5bcc44d88481d0a0cc4aacb3#b676c5123a0246798c75614dcb5f9f34

ColorCubeStorage.default.filters = [filter]
```
