### ISSUE TITLE
Flipped preview image (MetalImageView) on iOS 17 simulator

### ISSUE THREAD

**Issue by ShoMasegi** [FluidGroup/Brightroom#203]
## Overview

Using ClassicImageEditViewController, Flipped preview image (MetalImageView) on iOS 17 simulator.
Maybe workaround for Metal is no longer necessary on iOS 17 or later.
(Of course, it's working fine on the device.)

https://github.com/FluidGroup/Brightroom/blob/3b5ce3d3ca908bad62872875e11dea54145238c6/Sources/BrightroomUI/Shared/Components/ImageViews/MetalImageView.swift#L191-L209

| iOS 16.4 | iOS 17.0 |
|:----:|:----:|
|<image src="https://github.com/FluidGroup/Brightroom/assets/12663296/61562c1b-fdea-418e-856a-47da71ef1aee" width="375" />|<image src="https://github.com/FluidGroup/Brightroom/assets/12663296/d8a9694c-5913-4835-8bfb-8b3fd6de669e" width="375" />|
 > run Demo app → Editor → Example Square

## Environment

- Xcode 15.0 (15A240d)
- iOS 17.0 (21A328) - Simulator
- (iOS 16.4 (20E247) - Simulator)

**Comment by muukii** [comment]
I'll check

**Comment by muukii** [comment]
https://github.com/FluidGroup/Brightroom/pull/205
