### ISSUE TITLE
Dependacy warning on swift-concurrency-task-manager with SPM

### ISSUE THREAD

**Issue by tlacan** [FluidGroup/Brightroom#243]
## Overview
In my iOS project I use SPM with Brighroom and I have a warning which will be problematic in future SPM version.

Showing Recent Issues
'swift-concurrency-task-manager' dependency on 'https://github.com/apple/swift-collections.git' conflicts with dependency on 'https://github.com/FluidGroup/swift-collections' which has the same identity 'swift-collections'. this will be escalated to an error in future versions of SwiftPM.

This is due to conflict between apple official swift-concurrency-task-manager and FluidGroup fork which is use into Brightroom.

## Details
Is it still useful for you to use custom fork, may you use official package and having customisation 
in Brighroom to avoid the issue ?

## Reproduce version
2.10.1

**Comment by muukii** [comment]
@tlacan Thank you for reporting.
at the time, I had to use my own fork as they did not release the head.
but now it's available to use their official version.
Could you try using 3.0 beta version of Brightroom?  it might be resolved as Verge switched to main stream for swift-collections

**Comment by tlacan** [comment]
@muukii 
Thank you for the quick replay.
will close as it is not happening anymore with 3.0 beta indeed.
