### ISSUE TITLE
Xcode 16/iOS 18 Issues

### ISSUE THREAD

**Issue by michaelgrigoryanwork** [FluidGroup/Brightroom#255]
## Overview
Pod is not running on Xcode 16 and iOS 18, need some update here.

## Details
No details, just errors all over the pod.

## Reproduce version
Latest

**Comment by nagendra6969** [comment]
Same here.

**Comment by helloworldsmart** [comment]
Same here.

**Comment by helloworldsmart** [comment]
I uninstalled Brightroom using CocoaPods and switched to installing it via Swift Package Manager.

I replaced:

```swift
import Brightroom

```

with:

```swift
import BrightroomEngine
import BrightroomUI
```

 The app runs without any issues now.

**Comment by michaelgrigoryanwork** [comment]
@helloworldsmart thank you, everything works for me too.
